<?php
declare(strict_types=1);
/**
 * Parser Reflection API
 *
 * @copyright Copyright 2026, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Go\ParserReflection;

use Go\ParserReflection\Locator\CallableLocator;
use Go\ParserReflection\Locator\ComposerLocator;
use PHPUnit\Framework\TestCase;

/**
 * Tests for the PHP 8.6 scope-aware accessibility introspection API
 *
 * @see \Go\ParserReflection\ReflectionProperty::isReadable()
 * @see \Go\ParserReflection\ReflectionProperty::isWritable()
 */
class PropertyAccessibilityTest extends TestCase
{
    private const STUB_FILE = __DIR__ . '/Stub/FileWithPropertyAccessibility86.php';

    private const STUB_NAMESPACE = 'Go\\ParserReflection\\Stub\\';

    /**
     * Scope names for the accessibility matrix, keyed by a short label.
     * The special 'self' label is resolved to the declaring class of each property.
     *
     * @var array<string, string|null>
     */
    private const SCOPES = [
        'null'       => null,
        'root'       => self::STUB_NAMESPACE . 'AccessibilityRoot',
        'child'      => self::STUB_NAMESPACE . 'AccessibilityChild',
        'grandchild' => self::STUB_NAMESPACE . 'AccessibilityGrandChild',
        'unrelated'  => self::STUB_NAMESPACE . 'AccessibilityUnrelated',
    ];

    /**
     * Expected [isReadable, isWritable] values per property and scope label.
     *
     * Every row was generated by running the native PHP 8.6 reflection over the same
     * stub file, so these hard-coded values encode the exact native semantics and let
     * the suite verify them even on runtimes without the native API (PHP 8.5).
     *
     * @var array<string, array<string, array{bool, bool}>>
     */
    private const EXPECTED_MATRIX = [
        'AccessibilityParent::pub' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::prot' => ['null' => [false, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [false, false]],
        'AccessibilityParent::priv' => ['null' => [false, false], 'self' => [true, true], 'root' => [false, false], 'child' => [false, false], 'grandchild' => [false, false], 'unrelated' => [false, false]],
        'AccessibilityParent::pubProtSet' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, false]],
        'AccessibilityParent::pubPrivSet' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityParent::protPrivSet' => ['null' => [false, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [false, false]],
        'AccessibilityParent::ro' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, false]],
        'AccessibilityParent::roProt' => ['null' => [false, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [false, false]],
        'AccessibilityParent::roPriv' => ['null' => [false, false], 'self' => [true, true], 'root' => [false, false], 'child' => [false, false], 'grandchild' => [false, false], 'unrelated' => [false, false]],
        'AccessibilityParent::roPrivSet' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityParent::roPubSet' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::statPub' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::statProt' => ['null' => [false, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [false, false]],
        'AccessibilityParent::statPriv' => ['null' => [false, false], 'self' => [true, true], 'root' => [false, false], 'child' => [false, false], 'grandchild' => [false, false], 'unrelated' => [false, false]],
        'AccessibilityParent::virtGetOnly' => ['null' => [true, false], 'self' => [true, false], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityParent::virtSetOnly' => ['null' => [false, true], 'self' => [false, true], 'root' => [false, true], 'child' => [false, true], 'grandchild' => [false, true], 'unrelated' => [false, true]],
        'AccessibilityParent::virtBoth' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::backedGetHook' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::backedSetHook' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::backedBothHooks' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::protHooked' => ['null' => [false, false], 'self' => [true, false], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [false, false]],
        'AccessibilityParent::asymBackedHooked' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, false]],
        'AccessibilityParent::typedNoDefault' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::untyped' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityParent::promotedRo' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, false]],
        'AccessibilityParent::promotedPriv' => ['null' => [false, false], 'self' => [true, true], 'root' => [false, false], 'child' => [false, false], 'grandchild' => [false, false], 'unrelated' => [false, false]],
        'AccessibilityParent::promotedProtPrivSet' => ['null' => [false, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [false, false]],
        'AccessibilityChild::shadowPriv' => ['null' => [false, false], 'self' => [true, true], 'root' => [false, false], 'child' => [true, true], 'grandchild' => [false, false], 'unrelated' => [false, false]],
        'AccessibilityInterface::ifaceGetOnly' => ['null' => [true, false], 'self' => [true, false], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityInterface::ifaceGetSet' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityAbstract::absGetOnly' => ['null' => [true, false], 'self' => [true, false], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityAbstract::absSetOnly' => ['null' => [false, true], 'self' => [false, true], 'root' => [false, true], 'child' => [false, true], 'grandchild' => [false, true], 'unrelated' => [false, true]],
        'AccessibilityAbstract::absBoth' => ['null' => [true, true], 'self' => [true, true], 'root' => [true, true], 'child' => [true, true], 'grandchild' => [true, true], 'unrelated' => [true, true]],
        'AccessibilityAbstract::absPlainAsym' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityReadonlyClass::promotedInRoClass' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityEnum::name' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
        'AccessibilityEnum::value' => ['null' => [true, false], 'self' => [true, true], 'root' => [true, false], 'child' => [true, false], 'grandchild' => [true, false], 'unrelated' => [true, false]],
    ];

    protected function setUp(): void
    {
        // Stub file holds several classes at once, so it can not be resolved by the PSR-4 rules
        $locator = new CallableLocator(
            static fn(string $className): false|string
                => str_starts_with($className, self::STUB_NAMESPACE) ? self::STUB_FILE : false
        );
        ReflectionEngine::init($locator);
    }

    protected function tearDown(): void
    {
        ReflectionEngine::init(new ComposerLocator());
    }

    /**
     * This test intentionally goes first to check the pure AST-based path for the non-loaded classes
     */
    public function testAccessibilityMatrixWithoutLoadingClasses(): void
    {
        $parentClass = self::STUB_NAMESPACE . 'AccessibilityParent';
        if (!class_exists($parentClass, false)) {
            $wasNotLoaded = true;
        } else {
            // Another test may have loaded the stub already (e.g. when a single test is re-run)
            $wasNotLoaded = false;
        }

        foreach (self::EXPECTED_MATRIX as $classAndProperty => $expectations) {
            [$shortClassName, $propertyName] = explode('::', $classAndProperty);
            $declaringClassName = self::STUB_NAMESPACE . $shortClassName;
            $parsedProperty     = (new ReflectionClass($declaringClassName))->getProperty($propertyName);
            $this->assertInstanceOf(ReflectionProperty::class, $parsedProperty);

            foreach ($expectations as $scopeLabel => [$expectedReadable, $expectedWritable]) {
                $scope = ($scopeLabel === 'self') ? $declaringClassName : self::SCOPES[$scopeLabel];
                $this->assertSame(
                    $expectedReadable,
                    $parsedProperty->isReadable($scope),
                    "isReadable() for {$classAndProperty} from scope '{$scopeLabel}' should match native reflection"
                );
                $this->assertSame(
                    $expectedWritable,
                    $parsedProperty->isWritable($scope),
                    "isWritable() for {$classAndProperty} from scope '{$scopeLabel}' should match native reflection"
                );
            }
        }

        if ($wasNotLoaded) {
            $this->assertFalse(class_exists($parentClass, false), 'Static analysis should not load the classes');
        }
    }

    /**
     * Inherited properties resolved through a subclass keep the accessibility of the declaring class
     */
    public function testInheritedPropertyAccessibilityThroughSubclass(): void
    {
        $grandChildClass = new ReflectionClass(self::STUB_NAMESPACE . 'AccessibilityGrandChild');

        $inheritedProtected = $grandChildClass->getProperty('prot');
        $this->assertFalse($inheritedProtected->isReadable(null));
        $this->assertTrue($inheritedProtected->isReadable(self::SCOPES['root']));
        $this->assertTrue($inheritedProtected->isWritable(self::SCOPES['grandchild']));
        $this->assertFalse($inheritedProtected->isWritable(self::SCOPES['unrelated']));

        $inheritedPrivateSet = $grandChildClass->getProperty('protPrivSet');
        $this->assertTrue($inheritedPrivateSet->isReadable(self::SCOPES['grandchild']));
        $this->assertFalse($inheritedPrivateSet->isWritable(self::SCOPES['grandchild']));
        // Only the declaring class scope may write a private(set) property
        $this->assertTrue($inheritedPrivateSet->isWritable(self::STUB_NAMESPACE . 'AccessibilityParent'));

        $inheritedReadonly = $grandChildClass->getProperty('ro');
        $this->assertTrue($inheritedReadonly->isWritable(self::SCOPES['grandchild']));
        $this->assertFalse($inheritedReadonly->isWritable(null));
    }

    /**
     * Scope names are normalized the same way as native reflection: a leading backslash
     * is ignored and the class name comparison is case-insensitive
     */
    public function testScopeNameNormalization(): void
    {
        $parentClassName = self::STUB_NAMESPACE . 'AccessibilityParent';
        $parsedProperty  = (new ReflectionClass($parentClassName))->getProperty('priv');

        $this->assertTrue($parsedProperty->isReadable('\\' . $parentClassName));
        $this->assertTrue($parsedProperty->isReadable(strtoupper($parentClassName)));
        $this->assertFalse($parsedProperty->isReadable('\\' . self::STUB_NAMESPACE . 'AccessibilityUnrelated'));
    }

    /**
     * Native reflection resolves the scope class eagerly and fails with an Error for unknown names
     */
    public function testUnknownScopeClassThrowsError(): void
    {
        $parsedProperty = (new ReflectionClass(self::STUB_NAMESPACE . 'AccessibilityParent'))->getProperty('pub');

        try {
            $parsedProperty->isReadable('Go\\ParserReflection\\NoSuchScopeClass');
            $this->fail('An Error should be raised for the unknown scope class');
        } catch (\Error $exception) {
            $this->assertSame('Class "Go\\ParserReflection\\NoSuchScopeClass" not found', $exception->getMessage());
        }

        try {
            $parsedProperty->isWritable('');
            $this->fail('An Error should be raised for the empty scope class name');
        } catch (\Error $exception) {
            $this->assertSame('Class "" not found', $exception->getMessage());
        }
    }

    /**
     * The optional $object argument changes the result only for the initialization-dependent cases
     */
    public function testObjectDependentAccessibility(): void
    {
        include_once self::STUB_FILE;

        $parentClassName = self::STUB_NAMESPACE . 'AccessibilityParent';
        $parsedClass     = new ReflectionClass($parentClassName);
        $uninitialized   = new $parentClassName();
        $initialized     = new $parentClassName();
        $initialized->initAllReadonly();

        // A readonly property is writable on an object only while it is uninitialized
        $readonlyProperty = $parsedClass->getProperty('ro');
        $this->assertTrue($readonlyProperty->isWritable($parentClassName, $uninitialized));
        $this->assertFalse($readonlyProperty->isWritable(null, $uninitialized));
        $this->assertFalse($readonlyProperty->isWritable($parentClassName, $initialized));
        // ... and is readable only once it holds a value
        $this->assertFalse($readonlyProperty->isReadable($parentClassName, $uninitialized));
        $this->assertTrue($readonlyProperty->isReadable($parentClassName, $initialized));

        // Explicit public(set) readonly stays writable from the global scope while uninitialized
        $publicSetReadonly = $parsedClass->getProperty('roPubSet');
        $this->assertTrue($publicSetReadonly->isWritable(null, $uninitialized));
        $this->assertFalse($publicSetReadonly->isWritable(null, $initialized));

        // Non-readonly typed property: writable regardless of state, readable only when initialized
        $typedProperty = $parsedClass->getProperty('typedNoDefault');
        $this->assertTrue($typedProperty->isWritable(null, $uninitialized));
        $this->assertFalse($typedProperty->isReadable(null, $uninitialized));
        $withValue = new $parentClassName();
        $withValue->typedNoDefault = 42;
        $this->assertTrue($typedProperty->isReadable(null, $withValue));

        // Untyped property is always initialized (implicit null)
        $this->assertTrue($parsedClass->getProperty('untyped')->isReadable(null, $uninitialized));

        // A get hook short-circuits the initialization check, a set-only backing store does not
        $this->assertTrue($parsedClass->getProperty('backedGetHook')->isReadable(null, $uninitialized));
        $this->assertFalse($parsedClass->getProperty('backedSetHook')->isReadable(null, $uninitialized));
        $this->assertTrue($parsedClass->getProperty('backedSetHook')->isWritable(null, $uninitialized));

        // Promoted readonly property is initialized by the constructor
        $promotedReadonly = $parsedClass->getProperty('promotedRo');
        $this->assertTrue($promotedReadonly->isReadable(null, $uninitialized));
        $this->assertFalse($promotedReadonly->isWritable($parentClassName, $uninitialized));

        // A subclass instance is a valid object for the parent-declared property
        $childClassName = self::STUB_NAMESPACE . 'AccessibilityChild';
        $childInstance  = new $childClassName();
        $this->assertTrue($readonlyProperty->isWritable($parentClassName, $childInstance));

        // Enum cases always carry initialized readonly name/value properties
        $enumClassName = self::STUB_NAMESPACE . 'AccessibilityEnum';
        $enumCase      = $enumClassName::One;
        $enumNameProperty = (new ReflectionClass($enumClassName))->getProperty('name');
        $this->assertTrue($enumNameProperty->isReadable(null, $enumCase));
        $this->assertFalse($enumNameProperty->isWritable($enumClassName, $enumCase));
    }

    /**
     * Invalid $object arguments are rejected before the scope is even resolved
     */
    public function testObjectValidationErrors(): void
    {
        include_once self::STUB_FILE;

        $parentClassName = self::STUB_NAMESPACE . 'AccessibilityParent';
        $parsedClass     = new ReflectionClass($parentClassName);
        $parentInstance  = new $parentClassName();
        $unrelatedClass  = self::STUB_NAMESPACE . 'AccessibilityUnrelated';
        $unrelated       = new $unrelatedClass();

        // Objects are not allowed for static properties at all
        try {
            $parsedClass->getProperty('statPub')->isWritable($parentClassName, $parentInstance);
            $this->fail('A ReflectionException should be raised for an object on a static property');
        } catch (\ReflectionException $exception) {
            $this->assertSame('null is expected as object argument for static properties', $exception->getMessage());
        }

        // The object must be an instance of the declaring class
        try {
            $parsedClass->getProperty('pub')->isReadable($parentClassName, $unrelated);
            $this->fail('A ReflectionException should be raised for a foreign object');
        } catch (\ReflectionException $exception) {
            $this->assertSame(
                'Given object is not an instance of the class this property was declared in',
                $exception->getMessage()
            );
        }

        // Object validation happens before the scope resolution (native behaviour)
        try {
            $parsedClass->getProperty('pub')->isWritable('NoSuchScopeClass', $unrelated);
            $this->fail('The object check should fire before the unknown scope resolution');
        } catch (\ReflectionException $exception) {
            $this->assertSame(
                'Given object is not an instance of the class this property was declared in',
                $exception->getMessage()
            );
        }
        try {
            $parsedClass->getProperty('statPub')->isReadable('NoSuchScopeClass', $unrelated);
            $this->fail('The static property check should fire before the unknown scope resolution');
        } catch (\ReflectionException $exception) {
            $this->assertSame('null is expected as object argument for static properties', $exception->getMessage());
        }
    }

    /**
     * Full parity check with the native PHP 8.6 implementation: every stub property is
     * checked against every combination of scope and object, including error conditions
     */
    public function testNativeParity(): void
    {
        if (PHP_VERSION_ID < 80600) {
            $this->markTestSkipped('Native ReflectionProperty::isReadable()/isWritable() require PHP 8.6+');
        }

        include_once self::STUB_FILE;

        $parentClassName     = self::STUB_NAMESPACE . 'AccessibilityParent';
        $childClassName      = self::STUB_NAMESPACE . 'AccessibilityChild';
        $grandChildClassName = self::STUB_NAMESPACE . 'AccessibilityGrandChild';
        $unrelatedClassName  = self::STUB_NAMESPACE . 'AccessibilityUnrelated';
        $enumClassName       = self::STUB_NAMESPACE . 'AccessibilityEnum';

        $initializedParent = new $parentClassName();
        $initializedParent->initAllReadonly();

        $scopes = [
            null,
            self::STUB_NAMESPACE . 'AccessibilityRoot',
            $parentClassName,
            $childClassName,
            $grandChildClassName,
            $unrelatedClassName,
            self::STUB_NAMESPACE . 'AccessibilityInterface',
            '\\' . $parentClassName,
            strtoupper($childClassName),
            'Go\\ParserReflection\\NoSuchScopeClass',
            '',
        ];
        $objects = [
            'no-object'    => null,
            'uninit-parent' => new $parentClassName(),
            'init-parent'  => $initializedParent,
            'child'        => new $childClassName(),
            'grandchild'   => new $grandChildClassName(),
            'unrelated'    => new $unrelatedClassName(),
            'enum-case'    => $enumClassName::One,
        ];
        $classesToCheck = [
            $parentClassName,
            $childClassName,
            $grandChildClassName,
            self::STUB_NAMESPACE . 'AccessibilityInterface',
            self::STUB_NAMESPACE . 'AccessibilityAbstract',
            self::STUB_NAMESPACE . 'AccessibilityReadonlyClass',
            $enumClassName,
        ];

        $checkedCombinations = 0;
        foreach ($classesToCheck as $className) {
            $parsedClass = new ReflectionClass($className);
            foreach ((new \ReflectionClass($className))->getProperties() as $nativeProperty) {
                $parsedProperty = $parsedClass->getProperty($nativeProperty->getName());
                foreach ($scopes as $scope) {
                    foreach ($objects as $objectLabel => $object) {
                        foreach (['isReadable', 'isWritable'] as $methodName) {
                            $expected = $this->describeOutcome(
                                static fn(): bool => $nativeProperty->$methodName($scope, $object)
                            );
                            $actual = $this->describeOutcome(
                                static fn(): bool => $parsedProperty->$methodName($scope, $object)
                            );
                            $scopeLabel = $scope ?? '(null)';
                            $this->assertSame(
                                $expected,
                                $actual,
                                "{$methodName}() for {$className}::\${$nativeProperty->getName()} " .
                                "from scope '{$scopeLabel}' with object '{$objectLabel}' should match native reflection"
                            );
                            $checkedCombinations++;
                        }
                    }
                }
            }
        }

        $this->assertGreaterThan(0, $checkedCombinations);
    }

    /**
     * Normalizes a check result to a comparable string: a boolean value or an exception
     * family (\ReflectionException or \Error) with its message
     *
     * @param \Closure(): bool $check
     */
    private function describeOutcome(\Closure $check): string
    {
        try {
            return var_export($check(), true);
        } catch (\ReflectionException $exception) {
            return 'ReflectionException: ' . $exception->getMessage();
        } catch (\Error $exception) {
            return 'Error: ' . $exception->getMessage();
        }
    }
}
